feat: split combine and combineWithAllErrors into sync and async versions
supermacro/neverthrow pull request #404
Opened 2022-07-12 14:31 UTC by tam-carre

Resolves https://github.com/supermacro/neverthrow/issues/381

Introduces breaking API changes

This PR removes the `combine` and `combineWithAllErrors` exports and creates `Result.combine`, `Result.combineWithAllErrors`, `ResultAsync.combine`, `ResultAsync.combineWithAllErrors`.

The "Utilities" section of the README has been removed as it would become just references to Result and ResultAsync sections.

Note that this PR makes a slightly different use of `any` from the previous code, but it is equivalent.

2022-07-14 17:29 UTC, supermacro commented
ETA for review + approval is next week

2022-07-26 13:46 UTC, supermacro requested changes

2022-07-26 13:46 UTC, supermacro commented on package.json
> +  "version": "4.4.2",
Something seems odd here ... the `master` branch is already at 4.4.2, so we shouldn't be seeing a diff here.

2022-07-26 13:53 UTC, tam-carre commented
Don't know how to clean up the commit history, made a new PR: https://github.com/supermacro/neverthrow/pull/405

2022-07-26 14:05 UTC, tam-carre commented
clean pr: https://github.com/supermacro/neverthrow/pull/406

2022-07-26 14:05 UTC, closed without merging