andTee() / andThrough() to handle side-effects a bit easier (from issue #445)
supermacro/neverthrow pull request #467
Opened 2023-04-03 04:48 UTC by untidy-hair

closes #445 

Hi @supermacro! 
I opened [an issue with a suggestion](#445 ) about 2.5 months ago (Jan 17) but I think you have been very busy and I thought maybe a real code would save your time :)

I got a feedback comment in the original issue thread and I ended up having these two methods.

1. andTee()
```typescript
andTee(f: (t: T) => unknown): ResultAsync<T, E>
// Usage: validate below returns ResultAsync
validate(userInfoInput).andThen(buildUser).andTee(logEvent).andThen(notifyUserRegistration)....
```
2. andThrough()
```typescript
andThrough<F>(f: (t: T) => ResultAsync<unknown, F>): ResultAsync<T, E | F>
// Usage: validate below returns ResultAsync
validate(userInfoInput).andThen(buildUser).andThrough(persistUser).andThen(notifyUserRegistration)....
```

Both return the original input `okAsync<T>` upon success, but in case of error, `andTee()` ignores the error whereas `andThrough()` returns the new error `errAsync<F>`. The former is suitable for such as logging when you don't want to stop the main logic upon trivial side-effect failure and the latter is suitable when you want to stop the main logic upon a critical side-effect failure such as DB insertion error.

Origianlly I was going to use  the name `andTee` for no.2 above that passes error value in case of an error but considering the original meaning of "tee", even the error should not come back to the main "pipe" so I used the name for no.1 above instead. (But as I wrote in the original issue, there could be better names.)
 
And was also written in the original thread, this can be done with the current APIs but these two new methods will make it possible to write and understand each step of the logics more vividly (IMO) and I personally have cases I want to rewrite code with `andThrough()` for DB persistence as I explained here :)

Thanks in advance!

2023-05-29 15:56 UTC, brndt commented
@supermacro can you take a look on this please? It's quite useful feature to avoid boilerplate

2023-09-12 21:36 UTC, brndt commented
@supermacro bump :)

2023-10-09 10:02 UTC, supermacro commented
https://github.com/supermacro/neverthrow/issues/496

2023-10-31 19:38 UTC, guilherme-sato approved these changes

2023-12-06 03:41 UTC, untidy-hair commented
Hi @supermacro , have you had a chance to look at this PR? Thank you!

2024-08-25 08:22 UTC, m-shaka requested changes
Thank you for your contribution
Can you add docs about new features to README?

2024-08-25 08:22 UTC, m-shaka commented on tests/typecheck-tests.ts
> +    // (function it(_ = 'Infers error type when returning disjoint types (native scalar types)') {
This test should be executed

2024-08-25 08:22 UTC, m-shaka commented on src/result.ts
> +  }
```suggestion
  asyncAndThrough<R extends ResultAsync<unknown, unknown>>(
    f: (t: T) => R,
  ): ResultAsync<T, E | InferAsyncErrTypes<R>>
  asyncAndThrough<F>(f: (t: T) => ResultAsync<unknown, F>): ResultAsync<T, E | F>
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
  asyncAndThrough(f: (t: T) => ResultAsync<unknown, unknown>): any {
    return f(this.value).map(() => this.value)
  }
```
The signature should be overloaded and the error type should be union like `andThrough`.
If so, you can remove this comment out
https://github.com/supermacro/neverthrow/pull/467/files?w=1#diff-5e6df76f1ff5c2ddfbb0bee2e515236794778a429792a91d3b853bfecc884c16R471-R485

2024-08-25 08:22 UTC, m-shaka commented on src/result.ts
> +  asyncAndThrough<F>(_f: (t: T) => ResultAsync<unknown, F>): ResultAsync<T, E> {
```suggestion
  asyncAndThrough<F>(_f: (t: T) => ResultAsync<unknown, F>): ResultAsync<T, E | F> {
```

2024-08-26 04:28 UTC, m-shaka commented
@supermacro Hey Gio, I think `andTee` is a nice name, but what do you think of the name `andThrough`? Do you have any other ideas?

2024-08-28 03:45 UTC, untidy-hair commented
Hi @m-shaka and @supermacro , I updated the PR based on the suggestions as well as README. Thanks

2024-08-28 14:26 UTC, supermacro commented
Both names are ok with me! Don't think it's fair for me to come in so late and opine strongly here. Great job everyone .. and thanks for your patience :)

2024-08-28 14:28 UTC, supermacro approved these changes

2024-08-28 14:30 UTC, merged