Added arethetypeswrong to check built outputs
supermacro/neverthrow pull request #569
Opened 2024-08-20 08:36 UTC by mattpocock

2024-08-20 08:37 UTC, mattpocock commented on package.json
> +    "prepublish": "npm run build",
Moved to prepublish, since attw --pack runs npm pack, creating an infinite loop with prepack

2024-08-20 08:51 UTC, mattpocock commented on package.json
> +    "prepublishOnly": "npm run build",
Moved to prepublishOnly, since this only runs on publish instead of on pack.

attw --pack calls npm pack, so you end up in a nice infinite loop.

2024-09-06 13:53 UTC, dmmulroy requested changes
Hey @mattpocock - could you explain what `attw` is and why it's a useful tool for library authors as context? 🙏

2024-09-06 18:40 UTC, supermacro commented
This package / pr is still not clicking with respect to the bigger picture PR of https://github.com/supermacro/neverthrow/pull/570

In my head I am asking myself, "why do I need `@arethetypeswrong/cli` if we already have `tsc` doing typechecking that short-circuits on a typeerror".

> It's extremely useful for checking if the exported types are correct in the package.json. I wanted to add it to make sure that my tsup changes weren't breaking anything.

So this makes me think that this PR is purely here to ascertain that the change from rollup --> tsup is working as expected and nothing else, correct?

2024-09-06 19:08 UTC, mattpocock commented
@supermacro 

`tsc` and `attw` do different things. `tsc` checks that your code type checks. `attw` checks that other packages consuming your code can consume it. It prevents errors like mis-configuring `exports`.

More info in [this article](https://www.totaltypescript.com/how-to-create-an-npm-package#5-exports-main-and-arethetypeswrongcli).

You're right, it is partially a bridging PR to ensure that `tsup` makes no meaningful changes.

But it does have its own utility. In the future, you may want to consider adding multiple entrypoints to `neverthrow` to prevent the downsides of barrel files. `attw` would ensure that `exports` would still be configured correctly.

Overall, I like as much of the user experience as possible to be testable via CI. Checking that users can consume the code feels important. But if you don't want it checked on every CI run, I can understand that.

2024-10-09 13:24 UTC, dmmulroy commented
I think that this is positive change - @supermacro and @m-shaka could we adopt this and merge it to unblock #570?

2025-02-18 16:00 UTC, supermacro commented
Replaced by https://github.com/supermacro/neverthrow/pull/618

2025-02-18 16:00 UTC, closed without merging