Add custom message to _unsafeUnwrap*
supermacro/neverthrow pull request #590
Opened 2024-10-09 13:14 UTC by dmmulroy

### Pull Request Description

#### Summary
This PR introduces enhancements to the error handling mechanism within the codebase by allowing custom error messages to be specified. Additionally, it updates the README documentation and adds new test cases.

#### Changes Made
1. **README.md**:
   - Added documentation on how to conditionally add a custom error message that will propagate with the error object.
   - Provided an example to demonstrate the usage of the custom error message with a stack trace.

2. **`src/_internals/error.ts`**:
   - Updated the `ErrorConfig` interface to include an optional `message` property.

3. **`src/result.ts`**:
   - Modified the `_unsafeUnwrapErr` method in the `Ok` class to use the custom error message if provided, otherwise, it defaults to the existing message.
   - Updated the `_unsafeUnwrap` method in the `Err` class to use the custom error message if provided, otherwise, it defaults to the existing message.

4. **`tests/index.test.ts`**:
   - Added test cases to verify that custom error messages are correctly included when `_unsafeUnwrap` and `_unsafeUnwrapErr` are called with a custom message in the `Ok` and `Err` classes.

2024-10-15 17:06 UTC, macksal approved these changes

2024-10-24 01:08 UTC, supermacro commented
safe to close this, right?

2024-11-15 06:35 UTC, m-shaka requested changes
Can you resolve conflicts and revert formatter change of index.test.ts?

I know we should format and commit test files too and check them on CI, but before doing it prettier must be upgraded. I'm thinking replace prettier with biome instead, though

2024-11-17 04:10 UTC, dmmulroy commented
Ope yup sorry, this notification got buried - will update tomorrow!

2025-05-19 00:55 UTC, closed without merging